BUILD_DIR   ?= build/
ROOT_PREFIX ?= ../../../

PREFIX   := $(ROOT_PREFIX)event/
INCLUDES := -I$(ROOT_PREFIX) -I$(ROOT_PREFIX)include/ -I$(ROOT_PREFIX)include/event/

include $(ROOT_PREFIX)makefiles/makefile_pattern
