BUILD_DIR   ?= build/
ROOT_PREFIX ?= ../../../

PREFIX   := $(ROOT_PREFIX)plugin_examples/src/filter_russian/
INCLUDES := -I$(ROOT_PREFIX) -I$(ROOT_PREFIX)include/

include $(ROOT_PREFIX)makefiles/makefile_pattern
