BUILD_DIR   ?= build/
ROOT_PREFIX ?= ../../

PREFIX   := $(ROOT_PREFIX)filter/
INCLUDES := -I$(ROOT_PREFIX) -I$(ROOT_PREFIX)include/ -I$(ROOT_PREFIX)include/filter/

include $(ROOT_PREFIX)makefiles/makefile_pattern
