BUILD_DIR   ?= build/
ROOT_PREFIX ?= ../../

PREFIX   := $(ROOT_PREFIX)graphic/
INCLUDES := -I$(ROOT_PREFIX) -I$(ROOT_PREFIX)include/ -I$(ROOT_PREFIX)include/graphic/

include $(ROOT_PREFIX)makefiles/makefile_pattern
