BUILD_DIR   ?= build/
ROOT_PREFIX ?= ../../

PREFIX   := $(ROOT_PREFIX)tool/
INCLUDES := -I$(ROOT_PREFIX) -I$(ROOT_PREFIX)include/ -I$(ROOT_PREFIX)include/tool/

include $(ROOT_PREFIX)makefiles/makefile_pattern
